[package]
name = "nmg_first_crate"
license = "MIT OR Apache-2.0"
description = "My first crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
